apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bw-cloudflared-token-secret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bw-cloudflared-token-secret
spec:
  organizationId: "47f4a574-8e28-4371-8f37-b2e2016efe13"
  secretName: bw-cloudflared-token-secret
  map:
    - bwSecretId: e7eb9a93-4af5-4881-b19f-b2e5000960fc
      secretKeyName: token
  authToken:
    secretName: bw-auth-token
    secretKey: token
