apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cluster
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cluster
    namespace: cnpg-cluster-production
    version: 0.3.1
    includeCRDs: true
    valuesFile: ./values.yaml

resources:
  - ./ns.yaml