apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bw-keycloak-production-db-secret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bw-keycloak-production-db-secret
spec:
  organizationId: "47f4a574-8e28-4371-8f37-b2e2016efe13"
  secretName: bw-keycloak-production-db-secret
  map:
    - bwSecretId: 27ef7974-33fc-4cde-8a9e-b2e4003f5dbb
      secretKeyName: username
    - bwSecretId: 58ece7aa-25bd-4cdb-8ac6-b2e4003f4f40
      secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bw-keycloak-production-admin-secret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bw-keycloak-production-admin-secret
spec:
  organizationId: "47f4a574-8e28-4371-8f37-b2e2016efe13"
  secretName: bw-keycloak-production-admin-secret
  map:
    - bwSecretId: 05598141-79d0-404b-862d-b2e4003f1908
      secretKeyName: username
    - bwSecretId: 200668a3-a91d-42f3-a105-b2e4003f32eb
      secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token