apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-production-cnpg-cluster
spec:
  instances: 3
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: bw-keycloak-production-db-secret