apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    releaseName: keycloak
    namespace: keycloak-production
    version: 24.7.2
    includeCRDs: true
    valuesFile: ./values.yaml

resources:
  - ./ns.yaml
  - ./bw-secret.yaml
  - ./cnpg-cluster.yaml