postgresql:
  enabled: false
externalDatabase:
  existingSecret: bw-keycloak-production-db-secret
  existingSecretUserKey: username
  existingSecretPasswordKey: password
  host: keycloak-production-cnpg-cluster-rw.keycloak-production.svc
  user: keycloak
  database: keycloak
auth:
  existingSecret: bw-keycloak-production-admin-secret
  passwordSecretKey: password
replicaCount: 3
ingress:
  enabled: true
  hostname: keycloak.k8s.corp.ryacom.org
proxyHeaders: xforwarded