apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    namespace: traefik-system
    version: 35.4.0
    includeCRDs: true
    valuesFile: ./values.yaml

resources:
  - ./ns.yaml
  - ./bw-secret.yaml
  - ./dashboard-auth.yaml
