apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bw-netbox-production-db-secret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bw-netbox-production-db-secret
spec:
  organizationId: "47f4a574-8e28-4371-8f37-b2e2016efe13"
  secretName: bw-netbox-production-db-secret
  map:
    - bwSecretId: a186e49e-e069-4571-abf3-b2f9000ccc18
      secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bw-netbox-production-admin-secret
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bw-netbox-production-admin-secret
spec:
  organizationId: "47f4a574-8e28-4371-8f37-b2e2016efe13"
  secretName: bw-netbox-production-admin-secret
  map:
    - bwSecretId: a8da6773-05ad-4edf-9920-b2f9000d16cd
      secretKeyName: password
  authToken:
    secretName: bw-auth-token
    secretKey: token
