apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: netbox
    repo: https://charts.netbox.oss.netboxlabs.com/
    releaseName: netbox
    namespace: netbox-production
    version: 6.0.31
    includeCRDs: true
    valuesFile: ./values.yaml

resources:
  - ./ns.yaml
  - ./bw-secret.yaml
  - ./cnpg-cluster.yaml
