postgresql:
  enabled: false
externalDatabase:
  existingSecretName: bw-netbox-production-db-secret
  existingSecretKey: password
  host: netbox-production-cnpg-cluster-rw.netbox-production.svc
  username: netbox
  database: netbox
superuser:
  existingSecret: bw-netbox-production-admin-secret
replicaCount: 2
persistence:
  enabled: false
ingress:
  enabled: true
  hosts:
    - host: netbox.k8s.corp.ryacom.org
      paths:
        - /
