apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
spec:
  rules:
    - host: traefik.k8s.corp.ryacom.org
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: traefik-api
              port:
                name: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-default
  ports:
  - port: 8080
    name: traefik
    targetPort: 8080
    protocol: TCP
