apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    releaseName: harbor 
    namespace: harbor-production
    version: 1.17.0
    includeCRDs: true
    valuesFile: ./values.yaml
